swagger: "3.0.0"
info:
  version: "0.0.1"
  title: Phantasma
  description: ""

paths:
  /meta/version:
    get:
      summary: "Get the version of phantasma and minecraft running"
      responses:
        200:
          description: Version Info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VersionResponse"
      security:
        - access: ["meta:version:read"]
  
  /minecraft/list:
    get:
      summary: "List the players online"
      responses:
        200:
          description: Online players
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlayerList"
      security:
        - access: ["minecraft:list:read"]
      

components:
  schemas:
    VersionResponse:
      type: object
      properties: 
        phantasma:
          type: object
          properties: 
            version:
              type: integer
        minecraft:
          type: object
          properties: 
            version:
              type: string
            servertype:
              type: string
    PlayerName:
      type: string
      description: The username of the player
    PlayerList:
      type: array
      items: 
        type: PlayerName